#!/usr/bin/env python3
"""Build the photo/video manifests and download the photos.

Photos are pulled from the Substack CDN into ebook/images/photos/ so the EPUB and
PDF embed local files and never hotlink a gated host.

Videos get a manifest entry only. There is deliberately no reader-facing URL and
no QR code until a YouTube unlisted link exists: the Substack video host is
paid/private, so encoding it would hand readers a link they cannot open.
Existing youtube_url values in media/videos.yaml are always preserved.
"""
from __future__ import annotations

import argparse
import io
import json
import re
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

import yaml
from PIL import Image

from stills import incoming_files, load_stills, resolve_photo_path, upright
from paths import (
    MANUSCRIPT_DIR,
    MEDIA_DIR,
    PHOTOS_DIR,
    PHOTOS_JSON,
    REPO_ROOT,
    SOURCES_DIR,
    VIDEOS_YAML,
    VIDEO_URLS_YAML,
    load_book,
    load_videos,
)

UA = "Mozilla/5.0 (compatible; LogicPerformance-ebook-build/1.0)"

VIDEO_MARKER = re.compile(r"\[\[VIDEO-PUBLIC:\s*([^/\]]+?)\s*/\s*(\d+)\s*/\s*(.*?)\s*\]\](?!\])")
PHOTO_PENDING_MARKER = re.compile(r"\[\[PHOTO-PENDING:\s*([^/\]]+?)\s*/\s*(\d+)\s*/\s*(.*?)\s*\]\](?!\])")
FIGURE_SRC = re.compile(r'<img[^>]+src="images/photos/([^"]+)"')

VIDEOS_HEADER = """\
# Video manifest for 「{title}」
#
# GENERATED by scripts/build_media.py. Edit media/video-urls.yaml (the URL list)
# or the manuscript markers, then re-run; do not hand-edit this file.
#
# POLICY:
#   * video_url must be a target a reader can actually open. Two shapes pass:
#       - the author-verified Substack video endpoint
#         https://logicfitko.substack.com/api/v1/video/upload/{{id}}/src
#         which redirects to a signed Mux mp4 and needs no login
#       - a YouTube watch URL (channel: {channel}, unlisted), for anything
#         re-hosted later
#   * Substack POST pages (logicfitko.substack.com/p/…) are paywalled and are
#     never linked or encoded. scripts/make_qr.py rejects them.
#   * A slot with no video_url renders an empty QR box labelled
#     "공개 영상 주소 예정". No URL is ever invented.
#
# substack_media_id is the upload id, kept for asset matching.
#
# After changing a URL: scripts/make_qr.py && scripts/build.py
"""


# A5 at ~350 dpi needs roughly 1600 px on the long edge; anything more is weight
# the EPUB and PDF do not use.
MAX_EDGE = 1600
JPEG_QUALITY = 92


def optimise(data: bytes, dest, rotate_cw: int = 0) -> None:
    """Flatten onto white, honour EXIF (+ authored) rotation, cap the long edge."""
    with Image.open(io.BytesIO(data)) as image:
        image = upright(image, rotate_cw)
        if image.mode in ("RGBA", "LA", "P"):
            image = image.convert("RGBA")
            flattened = Image.new("RGB", image.size, (255, 255, 255))
            flattened.paste(image, mask=image.split()[-1])
            image = flattened
        else:
            image = image.convert("RGB")
        if max(image.size) > MAX_EDGE:
            scale = MAX_EDGE / max(image.size)
            image = image.resize(
                (round(image.width * scale), round(image.height * scale)), Image.LANCZOS
            )
        dest = Path(dest)
        dest.parent.mkdir(parents=True, exist_ok=True)
        image.save(dest, "JPEG", quality=JPEG_QUALITY, optimize=True, progressive=True)


def download(url: str, dest, tries: int = 3) -> bool:
    delay = 3
    for attempt in range(1, tries + 1):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": UA})
            with urllib.request.urlopen(req, timeout=90) as resp:
                data = resp.read()
            if not data:
                raise RuntimeError("empty response")
            optimise(data, dest)
            return True
        except (urllib.error.URLError, TimeoutError, RuntimeError) as exc:
            if attempt == tries:
                print(f"  ! failed {url}: {exc}", file=sys.stderr)
                return False
            time.sleep(delay)
            delay *= 2
    return False


def scan_manuscript() -> tuple[list[dict], list[dict], set[str]]:
    """Read the manuscript for video slots, pending stills, and figure filenames."""
    videos: list[dict] = []
    pending: list[dict] = []
    figures: set[str] = set()
    for path in sorted(MANUSCRIPT_DIR.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        for chapter, index, description in VIDEO_MARKER.findall(text):
            videos.append(
                {
                    "id": f"{chapter}-v{int(index):02d}",
                    "chapter": chapter,
                    "index": int(index),
                    "description": description,
                    "manuscript": path.name,
                }
            )
        for chapter, index, note in PHOTO_PENDING_MARKER.findall(text):
            pending.append({"chapter": chapter, "index": int(index), "note": note})
        figures.update(FIGURE_SRC.findall(text))
    return videos, pending, figures


def slots_from_urls() -> dict[str, dict]:
    """The supplied URL list defines which slots exist and in what order."""
    if not VIDEO_URLS_YAML.exists():
        return {}
    data = yaml.safe_load(VIDEO_URLS_YAML.read_text(encoding="utf-8")) or {}
    base = data.get("base") or ""
    slots: dict[str, dict] = {}
    for chapter, ids in (data.get("chapters") or {}).items():
        for index, media_id in enumerate(ids or [], 1):
            slot_id = f"{chapter}-v{index:02d}"
            slots[slot_id] = {
                "id": slot_id,
                "chapter": chapter,
                "index": index,
                "substack_media_id": media_id,
                "video_url": base.format(id=media_id) if base else None,
            }
    return slots


def merge_videos(found: list[dict]) -> dict:
    """Union of the supplied URL list and the markers present in the manuscript.

    The URL list decides which slots exist. Manuscript markers add the caption
    and, by their position, place a slot inline; a slot with no marker is laid
    out at the end of its chapter by build.py.
    """
    existing = {v["id"]: v for v in load_videos().get("videos") or []}
    from_urls = slots_from_urls()
    from_text = {slot["id"]: slot for slot in found}

    merged = []
    for slot_id in sorted(
        set(from_urls) | set(from_text) | set(existing),
        key=lambda s: (s.rsplit("-v", 1)[0], int(s.rsplit("-v", 1)[1])),
    ):
        url_slot = from_urls.get(slot_id, {})
        text_slot = from_text.get(slot_id, {})
        prior = existing.get(slot_id, {})
        chapter = url_slot.get("chapter") or text_slot.get("chapter") or prior.get("chapter")
        index = url_slot.get("index") or text_slot.get("index") or prior.get("index")
        merged.append(
            {
                "id": slot_id,
                "chapter": chapter,
                "index": index,
                "description": text_slot.get("description") or prior.get("description") or "",
                "substack_media_id": url_slot.get("substack_media_id")
                or prior.get("substack_media_id"),
                "video_url": url_slot.get("video_url") or prior.get("video_url"),
                "inline": slot_id in from_text,
            }
        )
    return {"videos": merged}


def dump_videos(manifest: dict) -> None:
    lines = [
        VIDEOS_HEADER.format(
            title=load_book()["title"],
            channel=load_book().get("video_channel") or "unset",
        ),
        "# Total clips in the compiled manuscript inventory, including the ones",
        "# inside posts whose body is not public yet.",
        "expected_total_from_manuscript_inventory: 54",
        "",
        "videos:",
    ]
    for slot in manifest["videos"]:
        lines.append(f"  - id: {slot['id']}")
        lines.append(f"    chapter: {slot['chapter']}")
        lines.append(f"    index: {slot['index']}")
        description = (slot.get("description") or "").replace('"', "'")
        lines.append(f'    description: "{description}"')
        media_id = slot.get("substack_media_id")
        lines.append(f"    substack_media_id: {media_id or 'null'}")
        url = slot.get("video_url")
        lines.append(f"    video_url: {url or 'null'}")
        # True when the manuscript has a marker fixing this slot's position.
        lines.append(f"    inline: {str(bool(slot.get('inline'))).lower()}")
        lines.append("")
    VIDEOS_YAML.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def ingest_incoming() -> int:
    """Copy author stills from images/incoming/ into images/photos/.

    Files named 01…06 (any suffix) map onto media/stills.yaml in that order.
    A file already sitting under its dest name is left alone.
    """
    stills = load_stills()
    if not stills:
        return 0
    incoming = incoming_files()
    written = 0
    if incoming:
        pairs = list(zip(incoming, stills))
        for src, still in pairs:
            dest = PHOTOS_DIR / still["dest"]
            dest.parent.mkdir(parents=True, exist_ok=True)
            optimise(src.read_bytes(), dest, rotate_cw=still.get("rotate_cw") or 0)
            print(
                f"  ingested {src.name} -> {dest.relative_to(REPO_ROOT)}"
                f" rotate_cw={still.get('rotate_cw') or 0}"
            )
            written += 1
    # Re-optimise dest files that were dropped in place as png/webp.
    for still in stills:
        dest = PHOTOS_DIR / still["dest"]
        if dest.exists():
            continue
        found = resolve_photo_path(still["dest"])
        if found and found.suffix.lower() != ".jpg":
            optimise(found.read_bytes(), dest, rotate_cw=still.get("rotate_cw") or 0)
            if found != dest:
                found.unlink()
            print(f"  flattened {found.name} -> {dest.relative_to(REPO_ROOT)}")
            written += 1
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--skip-download", action="store_true", help="manifests only")
    parser.add_argument("--redownload", action="store_true", help="refetch existing photos")
    args = parser.parse_args()

    MEDIA_DIR.mkdir(parents=True, exist_ok=True)
    PHOTOS_DIR.mkdir(parents=True, exist_ok=True)

    detected_path = SOURCES_DIR / "_detected_media.json"
    detected = (
        json.loads(detected_path.read_text(encoding="utf-8"))
        if detected_path.exists()
        else {"photos": []}
    )

    videos, pending_stills, figures = scan_manuscript()
    ingested = ingest_incoming()
    if ingested:
        print(f"stills ingested: {ingested}")

    # Photos: everything the manuscript references, plus authored still dests.
    by_file = {p["file"]: p for p in detected.get("photos", [])}
    for still in load_stills():
        figures.add(still["dest"])
    photos = []
    for filename in sorted(figures):
        record = by_file.get(filename, {})
        photos.append(
            {
                "file": filename,
                "chapter": record.get("chapter") or filename.split("-")[0],
                "caption": record.get("caption", ""),
                "source_url": record.get("source_url"),
            }
        )

    downloaded = missing = skipped = 0
    for photo in photos:
        dest = PHOTOS_DIR / photo["file"]
        if dest.exists() and not args.redownload:
            photo["status"] = "present"
            skipped += 1
            continue
        if args.skip_download or not photo["source_url"]:
            photo["status"] = "missing"
            missing += 1
            continue
        if download(photo["source_url"], dest):
            photo["status"] = "downloaded"
            downloaded += 1
        else:
            photo["status"] = "missing"
            missing += 1

    PHOTOS_JSON.write_text(
        json.dumps(
            {
                "photos": photos,
                "pending_stills": pending_stills,
                "expected_total_from_manuscript_inventory": 64,
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    manifest = merge_videos(videos)
    dump_videos(manifest)

    with_url = sum(1 for v in manifest["videos"] if v.get("video_url"))
    print(f"photos:  {len(photos)} referenced  {downloaded} downloaded  {skipped} already present  {missing} missing")
    inline = sum(1 for v in manifest["videos"] if v.get("inline"))
    print(
        f"videos:  {len(manifest['videos'])} slots  {with_url} with a playable URL  "
        f"{inline} placed inline by a manuscript marker"
    )
    print(f"pending stills: {len(pending_stills)}")
    print(f"wrote {PHOTOS_JSON.relative_to(REPO_ROOT)}")
    print(f"wrote {VIDEOS_YAML.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
