#!/usr/bin/env python3
"""Draw the cover art and the part-opener plates.

Every plate is drawn here rather than generated by an image model, so the book
carries no invented photographs and no burned-in lettering: all type is set in
WeasyPrint from book.yaml. The marks are the ones the author asked for — an
open circle for the cover, footprints on a broken path, a diagnostic grid, the
swing clock, three flight arcs, and a small index mark for the appendix.

The printed feel comes from simulating a lino/letterpress pull rather than from
a texture photograph: a shape is drawn at 3x, blurred into a soft edge field,
then thresholded against layered value noise so the ink bites unevenly, holds
sparse pinholes, and varies in pressure across the stroke. The seed is fixed,
so the same plates come out of every build.

Palette is locked to the paper cream, pine ink green, and charcoal in
templates/common.css.
"""
from __future__ import annotations

import math

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

from paths import IMAGES_DIR, REPO_ROOT

PAPER = (246, 243, 234)
PINE = (47, 92, 62)
CHARCOAL = (38, 44, 40)

# Part plates share the 3:2 proportion of the author's studies.
PLATE = (1500, 1000)
COVER = (1748, 2480)  # A5 at 300dpi
MARK = (460, 460)

SS = 3  # supersample factor for shape drawing


# --------------------------------------------------------------------------
# ink engine
# --------------------------------------------------------------------------


class Plate:
    """A sheet of paper that shapes can be pressed onto in one or more inks."""

    def __init__(
        self,
        size: tuple[int, int],
        seed: int,
        paper: bool = True,
        vignette: float = 0.0,
    ) -> None:
        self.w, self.h = size
        self.rng = np.random.default_rng(seed)
        self.opaque = paper
        if paper:
            self.rgb = self._paper(vignette)
            self.alpha = np.ones((self.h, self.w), dtype=np.float32)
        else:
            self.rgb = np.zeros((self.h, self.w, 3), dtype=np.float32)
            self.alpha = np.zeros((self.h, self.w), dtype=np.float32)

    # ---- noise -----------------------------------------------------------

    def _noise(self, cells: int) -> np.ndarray:
        """Smooth value noise: random lattice upsampled bicubically."""
        ch = max(2, int(cells * self.h / max(self.w, 1)))
        grid = (self.rng.random((ch, cells)) * 255).astype(np.uint8)
        up = Image.fromarray(grid, "L").resize((self.w, self.h), Image.BICUBIC)
        return np.asarray(up, dtype=np.float32) / 255.0

    def _paper(self, vignette: float) -> np.ndarray:
        """Cream stock: warm base and faint fibre.

        A part plate is drawn without any vignette so its edge dissolves into
        the cream page rather than printing as a visible rectangle. Only the
        full-bleed cover, which has no edge to hide, takes any shading.
        """
        base = np.zeros((self.h, self.w, 3), dtype=np.float32)
        base[:, :] = PAPER

        fibre = self._noise(max(40, self.w // 12)) - 0.5
        grain = self._noise(max(140, self.w // 4)) - 0.5
        sheet = base + (fibre * 6.0 + grain * 3.0)[:, :, None]

        if vignette:
            ys = np.linspace(-1.0, 1.0, self.h, dtype=np.float32)[:, None]
            xs = np.linspace(-1.0, 1.0, self.w, dtype=np.float32)[None, :]
            sheet = sheet * (1.0 - vignette * (xs**2 + ys**2))[:, :, None]

        return np.clip(sheet, 0, 255)

    # ---- drawing ---------------------------------------------------------

    def canvas(self) -> tuple[Image.Image, ImageDraw.ImageDraw]:
        img = Image.new("L", (self.w * SS, self.h * SS), 0)
        return img, ImageDraw.Draw(img)

    def press(
        self,
        shape: Image.Image,
        color: tuple[int, int, int],
        bite: float = 0.22,
        soften: int = 4,
        starve: float = 0.985,
        wear: float = 0.18,
    ) -> None:
        """Press one drawn mask onto the sheet as inked, imperfect coverage.

        `bite` is how far the noise is allowed to push the edge in and out,
        `starve` how rarely the ink lifts off entirely, and `wear` how much the
        lay-down thins across the sheet.
        """
        cov = shape.resize((self.w, self.h), Image.LANCZOS)
        soft = np.asarray(cov.filter(ImageFilter.GaussianBlur(soften)), dtype=np.float32) / 255.0

        # Edge roughness has to be fine-grained or it reads as a wobble rather
        # than as a cut block: most of the bite comes from a near-pixel lattice.
        tooth = 0.30 * self._noise(11) + 0.70 * self._noise(max(220, self.w // 5))
        field = soft - bite * (tooth - 0.5) * 2.0
        alpha = np.clip((field - 0.5) / 0.11 + 0.5, 0.0, 1.0)

        # Broad thin patches, the way a hand-pulled print loses ink unevenly.
        pressure = 0.6 * self._noise(8) + 0.4 * self._noise(24)
        alpha *= 1.0 - wear * np.clip(pressure - 0.42, 0, 1) * 2.0

        # A very few starved specks. Kept sparse and grey, never white confetti.
        speck = self._noise(max(260, self.w // 3))
        alpha = np.where(speck > starve, alpha * 0.55, alpha)
        alpha = np.clip(alpha, 0.0, 1.0)

        ink = np.zeros((self.h, self.w, 3), dtype=np.float32)
        ink[:, :] = color
        # Thin ink reads slightly lighter than a full lay-down.
        ink = ink + np.clip(0.62 - pressure, 0, 1)[:, :, None] * 26.0

        ink = np.clip(ink, 0, 255)
        if self.opaque:
            a = alpha[:, :, None]
            self.rgb = self.rgb * (1 - a) + ink * a
        else:
            # Straight alpha, so the ink colour has to be stored unmultiplied or
            # the soft edges wash out wherever the plate is laid over a page.
            fresh = (alpha > self.alpha)[:, :, None]
            self.rgb = np.where(fresh, ink, self.rgb)
        self.alpha = np.maximum(self.alpha, alpha)

    def save(self, name: str) -> None:
        """Write the plate.

        Paper grain is noise, and noise is the worst case for PNG, so an opaque
        plate ships as a JPEG: same look, a twentieth of the bytes.
        """
        dest = IMAGES_DIR / "plates" / name
        dest.parent.mkdir(parents=True, exist_ok=True)
        rgb = np.clip(self.rgb, 0, 255).astype(np.uint8)
        if dest.suffix == ".jpg":
            Image.fromarray(rgb, "RGB").save(dest, "JPEG", quality=92, optimize=True)
        else:
            rgba = np.dstack([rgb, (self.alpha * 255.0).astype(np.uint8)])
            Image.fromarray(rgba, "RGBA").save(dest, "PNG", optimize=True)
        print(f"  {dest.relative_to(REPO_ROOT)}  {self.w}x{self.h}  {dest.stat().st_size // 1024} KB")


# --------------------------------------------------------------------------
# stroke primitives, all in supersampled pixels
# --------------------------------------------------------------------------


def dot(draw: ImageDraw.ImageDraw, x: float, y: float, r: float) -> None:
    draw.ellipse([x - r, y - r, x + r, y + r], fill=255)


def arc(
    draw: ImageDraw.ImageDraw,
    cx: float,
    cy: float,
    r: float,
    a0: float,
    a1: float,
    w0: float,
    w1: float | None = None,
    gaps: tuple[tuple[float, float], ...] = (),
    steps: int = 900,
) -> None:
    """A brush-drawn arc whose nib tapers from w0 to w1, minus any gaps."""
    w1 = w0 if w1 is None else w1
    for i in range(steps + 1):
        u = i / steps
        if any(lo <= u <= hi for lo, hi in gaps):
            continue
        ang = math.radians(a0 + (a1 - a0) * u)
        dot(draw, cx + r * math.cos(ang), cy + r * math.sin(ang), w0 + (w1 - w0) * u)


def bezier(
    draw: ImageDraw.ImageDraw,
    p0: tuple[float, float],
    p1: tuple[float, float],
    p2: tuple[float, float],
    w0: float,
    w1: float | None = None,
    steps: int = 700,
) -> None:
    w1 = w0 if w1 is None else w1
    for i in range(steps + 1):
        u = i / steps
        x = (1 - u) ** 2 * p0[0] + 2 * (1 - u) * u * p1[0] + u**2 * p2[0]
        y = (1 - u) ** 2 * p0[1] + 2 * (1 - u) * u * p1[1] + u**2 * p2[1]
        dot(draw, x, y, w0 + (w1 - w0) * u)


def bar(
    draw: ImageDraw.ImageDraw,
    x0: float,
    y0: float,
    x1: float,
    y1: float,
    w: float,
    dashes: tuple[tuple[float, float], ...] = ((0.0, 1.0),),
) -> None:
    for lo, hi in dashes:
        for i in range(400):
            u = lo + (hi - lo) * i / 399
            dot(draw, x0 + (x1 - x0) * u, y0 + (y1 - y0) * u, w)


def rotate_about(
    pts: list[tuple[float, float]], cx: float, cy: float, rot: float
) -> list[tuple[float, float]]:
    ca, sa = math.cos(math.radians(rot)), math.sin(math.radians(rot))
    return [((x - cx) * ca - (y - cy) * sa + cx, (x - cx) * sa + (y - cy) * ca + cy) for x, y in pts]


# Half-width of a shoe sole down its length: toe, ball, waist, heel. Kept near
# 1:3 against the length, which is roughly what a real sole prints.
SOLE_T = (0.00, 0.05, 0.13, 0.24, 0.37, 0.50, 0.60, 0.70, 0.82, 0.93, 1.00)
SOLE_W = (0.050, 0.115, 0.152, 0.166, 0.158, 0.124, 0.104, 0.113, 0.137, 0.127, 0.055)


def footprint(
    draw: ImageDraw.ImageDraw,
    cx: float,
    cy: float,
    length: float,
    rot: float = 0.0,
) -> None:
    """A pressed shoe sole: ball and heel joined by a waist, split by a gap.

    Drawn as one outline so the two pads stay in register, then the arch band is
    lifted back out — which is what a real sole leaves on the ground.
    """
    top = cy - length / 2
    right = [
        (cx + length * np.interp(t, SOLE_T, SOLE_W), top + length * t) for t in np.linspace(0, 1, 90)
    ]
    left = [
        (cx - length * np.interp(t, SOLE_T, SOLE_W), top + length * t)
        for t in np.linspace(1, 0, 90)
    ]
    draw.polygon(rotate_about(right + left, cx, cy, rot), fill=255)

    # Lift the arch: a shoe prints the ball and the heel, not the bridge.
    band_y = top + length * 0.615
    half = length * 0.20
    gap = [
        (cx - half, band_y - length * 0.028),
        (cx + half, band_y - length * 0.028),
        (cx + half, band_y + length * 0.028),
        (cx - half, band_y + length * 0.028),
    ]
    draw.polygon(rotate_about(gap, cx, cy, rot), fill=0)


def arrowhead(
    draw: ImageDraw.ImageDraw,
    x: float,
    y: float,
    heading: float,
    length: float,
    half_width: float,
) -> None:
    """A triangle whose base sits at (x, y) and whose tip runs along heading."""
    a = math.radians(heading)
    along = (math.cos(a), math.sin(a))
    across = (-along[1], along[0])
    draw.polygon(
        [
            (x + length * along[0], y + length * along[1]),
            (x + half_width * across[0], y + half_width * across[1]),
            (x - half_width * across[0], y - half_width * across[1]),
        ],
        fill=255,
    )


# --------------------------------------------------------------------------
# the plates
# --------------------------------------------------------------------------


def cover_art() -> None:
    """Full-bleed cover stock with the open circle low on the page.

    Type is not drawn here. The arc sits in the lower half so the title,
    subtitle and byline set in CSS have quiet paper to stand on.
    """
    plate = Plate(COVER, seed=1101, vignette=0.05)
    w, h = plate.w * SS, plate.h * SS
    img, draw = plate.canvas()

    cx, cy, r = w * 0.5, h * 0.605, w * 0.232
    # One brush sweep that never closes: thin where the stroke lands, heaviest
    # through the bottom left, thin again as it lifts. Two passes because the
    # nib only tapers one way per pass.
    arc(draw, cx, cy, r, 96, 268, w * 0.0098, w * 0.0205)
    arc(draw, cx, cy, r, 268, 398, w * 0.0205, w * 0.0062)
    # A second, wider sweep past the opening — the arc the swing actually travels.
    arc(draw, cx, cy, r * 1.15, 26, 122, w * 0.0140, w * 0.0020)
    plate.press(img, PINE, bite=0.19, soften=6, starve=0.988)
    plate.save("cover-art.jpg")


def part1_footprints() -> None:
    """1부 — two prints standing on a path that breaks up as it turns."""
    plate = Plate(PLATE, seed=2201)
    w, h = plate.w * SS, plate.h * SS

    img, draw = plate.canvas()
    # The path sweeps in from the left, curls round behind the feet and breaks up.
    arc(
        draw,
        w * 0.44,
        h * 0.575,
        w * 0.26,
        -152,
        58,
        w * 0.0125,
        w * 0.0105,
        gaps=((0.13, 0.165), (0.30, 0.335), (0.47, 0.505), (0.64, 0.675), (0.81, 0.845)),
    )
    bar(
        draw,
        w * 0.03,
        h * 0.895,
        w * 0.42,
        h * 0.895,
        w * 0.0115,
        dashes=((0.0, 0.45), (0.55, 0.88), (0.95, 1.0)),
    )
    plate.press(img, PINE, bite=0.24, soften=5)

    img, draw = plate.canvas()
    footprint(draw, w * 0.415, h * 0.585, h * 0.42, rot=-7.0)
    footprint(draw, w * 0.545, h * 0.475, h * 0.42, rot=-13.0)
    plate.press(img, CHARCOAL, bite=0.20, soften=4, starve=0.992)
    plate.save("part-1-footprints.jpg")


def part2_grid() -> None:
    """2부 — an empty diagnostic grid with one cell stamped.

    Deliberately not a photograph and not a filled table: the part is about
    finding which cell your own miss lands in.
    """
    plate = Plate(PLATE, seed=3301)
    w, h = plate.w * SS, plate.h * SS
    cols, rows = 4, 3
    x0, y0 = w * 0.13, h * 0.20
    cw, ch = (w * 0.74) / cols, (h * 0.60) / rows

    img, draw = plate.canvas()
    for c in range(cols + 1):
        bar(draw, x0 + c * cw, y0, x0 + c * cw, y0 + rows * ch, w * 0.0035)
    for r in range(rows + 1):
        bar(draw, x0, y0 + r * ch, x0 + cols * cw, y0 + r * ch, w * 0.0035)
    plate.press(img, CHARCOAL, bite=0.15, soften=3, starve=0.986)

    img, draw = plate.canvas()
    # One cell is answered; the rest wait for the reader's own assessment.
    ccx, ccy = x0 + cw * 2.5, y0 + ch * 1.5
    arc(draw, ccx, ccy, min(cw, ch) * 0.36, 0, 360, w * 0.0052)
    plate.press(img, PINE, bite=0.28, soften=6)
    plate.save("part-2-grid.jpg")


def part3_clock() -> None:
    """3부 — the swing clock: a dial with the down-and-through sweep in green."""
    plate = Plate(PLATE, seed=4401)
    w, h = plate.w * SS, plate.h * SS
    cx, cy, r = w * 0.5, h * 0.5, h * 0.335

    img, draw = plate.canvas()
    arc(draw, cx, cy, r, 0, 360, w * 0.0095)
    for angle in (270, 0, 90, 180):
        a = math.radians(angle)
        bar(
            draw,
            cx + r * 0.845 * math.cos(a),
            cy + r * 0.845 * math.sin(a),
            cx + r * 0.955 * math.cos(a),
            cy + r * 0.955 * math.sin(a),
            w * 0.0075,
        )
    plate.press(img, CHARCOAL, bite=0.30, soften=6)

    img, draw = plate.canvas()
    # Down to six o'clock and back up: the path the book keeps returning to.
    # Both ends carry a head, because the reader travels the arc in both halves.
    left_end = (cx - r * 0.52, cy - r * 0.40)
    low = (cx + r * 0.02, cy + r * 0.58)
    right_end = (cx + r * 0.66, cy - r * 0.32)
    bezier(draw, left_end, (cx - r * 0.60, cy + r * 0.34), low, w * 0.0080, w * 0.0110)
    bezier(draw, low, (cx + r * 0.62, cy + r * 0.44), right_end, w * 0.0110, w * 0.0078)
    arrowhead(draw, left_end[0], left_end[1], -104, w * 0.040, w * 0.026)
    arrowhead(draw, right_end[0], right_end[1], -62, w * 0.040, w * 0.026)
    plate.press(img, PINE, bite=0.20, soften=5)
    plate.save("part-3-clock.jpg")


def part4_arcs() -> None:
    """4부 — three ball flights off one launch point. No labels: the chapters name them."""
    plate = Plate(PLATE, seed=5501)
    w, h = plate.w * SS, plate.h * SS
    ground = h * 0.845
    launch = (w * 0.105, ground)

    img, draw = plate.canvas()
    bar(draw, w * 0.02, ground, w * 0.98, ground, w * 0.0045)
    plate.press(img, CHARCOAL, bite=0.34, soften=8, starve=0.88, wear=0.34)

    img, draw = plate.canvas()
    flights = (
        ((w * 0.52, h * 0.030), (w * 0.905, h * 0.545)),
        ((w * 0.50, h * 0.300), (w * 0.930, h * 0.660)),
        ((w * 0.48, h * 0.590), (w * 0.955, h * 0.775)),
    )
    for control, end in flights:
        bezier(draw, launch, control, end, w * 0.0032)
        dot(draw, end[0], end[1], w * 0.0075)
    plate.press(img, CHARCOAL, bite=0.11, soften=2, starve=0.995, wear=0.10)
    plate.save("part-4-arcs.jpg")


def figure_hi_launch() -> None:
    """4부 챕터 3 — one high launch and a short landing.

    Replaces a photoreal golfer on a mountain course. No person, no face, no
    fairway, no club: the chapter is about the shape of the flight, so the plate
    draws only the flight.
    """
    # Shorter frame than a part plate: this one sits inline, so it should not
    # carry a part opener's worth of empty paper.
    plate = Plate((1500, 820), seed=7701)
    w, h = plate.w * SS, plate.h * SS
    ground = h * 0.90
    launch = (w * 0.20, ground)

    img, draw = plate.canvas()
    bar(draw, w * 0.04, ground, w * 0.96, ground, w * 0.0045)
    plate.press(img, CHARCOAL, bite=0.34, soften=8, starve=0.88, wear=0.34)

    img, draw = plate.canvas()
    # The control sits above the frame so the flight actually climbs: a quadratic
    # only reaches halfway to its control point.
    end = (w * 0.80, ground)
    bezier(draw, launch, (w * 0.50, -h * 0.30), end, w * 0.0034)
    # It lands steeply and stops, so the mark ends on the ground.
    dot(draw, end[0], end[1] - h * 0.008, w * 0.0075)
    plate.press(img, CHARCOAL, bite=0.11, soften=2, starve=0.995, wear=0.10)
    plate.save("fig-hi-launch.jpg")


def play_mark() -> None:
    """Small ink poster for EPUB video slots: the cover's open circle + a triangle.

    Drawn, not generated. No person, no club, no course. Print does not use it.
    """
    # Cream stock, not transparency: many reading systems ignore PNG alpha and
    # would otherwise print a black square behind the mark.
    plate = Plate((640, 640), seed=8801, paper=True)
    w, h = plate.w * SS, plate.h * SS
    cx, cy, r = w * 0.5, h * 0.5, w * 0.34

    img, draw = plate.canvas()
    # Same language as the cover: one sweep that never closes.
    arc(draw, cx, cy, r, 108, 428, w * 0.014, w * 0.008)
    plate.press(img, PINE, bite=0.20, soften=5, starve=0.99)

    img, draw = plate.canvas()
    # Play triangle in the opening, pointing through the gap.
    arrowhead(draw, cx - w * 0.03, cy, 0, w * 0.16, w * 0.11)
    plate.press(img, PINE, bite=0.22, soften=4)
    plate.save("play-mark.png")


def appendix_mark() -> None:
    """부록 — a small index mark, nothing figurative.

    Ink on transparency rather than on stock: the appendix runs on white text
    pages, so the mark has to sit on whatever the page is.
    """
    plate = Plate(MARK, seed=6601, paper=False)
    w, h = plate.w * SS, plate.h * SS

    img, draw = plate.canvas()
    bar(draw, w * 0.30, h * 0.24, w * 0.30, h * 0.76, w * 0.022)
    bar(draw, w * 0.30, h * 0.24, w * 0.52, h * 0.24, w * 0.022)
    bar(draw, w * 0.30, h * 0.76, w * 0.52, h * 0.76, w * 0.022)
    dot(draw, w * 0.68, h * 0.50, w * 0.055)
    plate.press(img, PINE, bite=0.26, soften=5)
    plate.save("appendix-mark.png")


def main() -> int:
    print("plates")
    cover_art()
    part1_footprints()
    part2_grid()
    part3_clock()
    part4_arcs()
    figure_hi_launch()
    appendix_mark()
    play_mark()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
